### ISSUE TITLE
关于genOverfittingPatches.py无法处理patches/Large/correct/Many下补丁的问题

### ISSUE THREAD

**Issue by HJX-zhanS** [Ringbo/Cache#3]
您好，我在运行genOverfittingPatches.py时，发现该代码无法处理patches/Large/correct/Many下的补丁。请问应该如何解决？谢谢

**Comment by Ringbo** [comment]
你好。
Many下的补丁不属于现有的benchmark，而genOverfittingPatches依赖benchamrk对错误/正确文件进行提取。可以参考[此处](https://github.com/Ringbo/Cache/issues/1)对错误/正确文件进行提取。

**Comment by HJX-zhanS** [comment]
谢谢
